import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<div>
  <Link href="/" className='fixed z-10 top-10 left-10 text-gray-300 hover:text-white'>
      Home
  </Link>
  {children}
  
  <Link href="/roadmap" className="fixed z-10 top-10 right-10 text-gray-300 hover:text-white">
      Roadmap
  </Link>
</div>
  )
}
